CREATE TABLE Parents
(
	  ID INT
	, Document NVARCHAR(15)
	, FirstName NVARCHAR(15)
	, FamilyName NVARCHAR(15)
	, MiddleName NVARCHAR(15)
	, BirthDate DATE
	, Gender NCHAR(2)
);

ALTER TABLE Parents
ALTER COLUMN ID INT NOT NULL;

ALTER TABLE Parents
ADD CONSTRAINT c_PK_Parents
PRIMARY KEY (ID);

ALTER TABLE Parents
ALTER COLUMN Document NVARCHAR(15)
NOT NULL;

ALTER TABLE Parents
ADD CONSTRAINT u_Doc_Parents
UNIQUE(Document);

--ALTER TABLE Parents
--DROP CONSTRAINT u_Doc_Parents;

ALTER TABLE Parents
ALTER COLUMN FirstName NVARCHAR(15) NOT NULL;

ALTER TABLE Parents
ALTER COLUMN FamilyName NVARCHAR(15) NOT NULL;

ALTER TABLE Parents
ALTER COLUMN BirthDate DATE
NOT NULL;

ALTER TABLE Parents
ALTER COLUMN 
Gender NCHAR(2)
NOT NULL;